# Generated by Django 5.0.1 on 2024-02-01 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='data',
            new_name='date',
        ),
    ]
